// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Email              string `json:"email"`
	Firstname          string `json:"firstname"`
	Lastname           string `json:"lastname"`
	Password           string `json:"password"`
	Profilephotourl    string `json:"profilephotourl"`
	Backgroundphotourl string `json:"backgroundphotourl"`
	Headline           string `json:"headline"`
	Pronouns           string `json:"pronouns"`
	Profilelink        string `json:"profilelink"`
	About              string `json:"about"`
	Location           string `json:"location"`
	Isactive           bool   `json:"isactive"`
}

type User struct {
	ID                 string `json:"id"`
	Email              string `json:"email"`
	Firstname          string `json:"firstname"`
	Lastname           string `json:"lastname"`
	Password           string `json:"password"`
	Profilephotourl    string `json:"profilephotourl"`
	Backgroundphotourl string `json:"backgroundphotourl"`
	Headline           string `json:"headline"`
	Pronouns           string `json:"pronouns"`
	Profilelink        string `json:"profilelink"`
	About              string `json:"about"`
	Location           string `json:"location"`
	Isactive           bool   `json:"isactive"`
}
